# Target-related function and macro definitions for RPCEmu.
	
macro(rpcemu_add_executables)
	qt_add_executable(qt6-interpreter
		${EMBEDDED_RESOURCES}
		${COMMON_HEADERS} 
		${COMMON_SOURCES} 
		${INTEROP_HEADERS}
		${INTEROP_SOURCES}
		${INTERPRETER_HEADERS} 
		${INTERPRETER_SOURCES} 
		${PLATFORM_INTEROP_HEADERS}
		${PLATFORM_INTEROP_SOURCES}
		${PLATFORM_HEADERS} 
		${PLATFORM_SOURCES}
	)

	qt_add_executable(qt6-recompiler
		${EMBEDDED_RESOURCES}
		${COMMON_HEADERS} 
		${COMMON_SOURCES}
		${INTEROP_HEADERS}
		${INTEROP_SOURCES}
		${RECOMPILER_HEADERS}
		${RECOMPILER_SOURCES}
		${PLATFORM_INTEROP_HEADERS}
		${PLATFORM_INTEROP_SOURCES}
		${PLATFORM_RECOMPILER_HEADERS}
		${PLATFORM_RECOMPILER_SOURCES}
		${PLATFORM_HEADERS} 
		${PLATFORM_SOURCES}
	)
endmacro(rpcemu_add_executables)