/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "rpcemu"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "rpcemu"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "rpcemu 0.7"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "rpcemu"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.7"

/* Version number of package */
#define VERSION "0.7"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */
